debug = false
servers = ["public"]

[db]
# Can also be set with the APP_DB_URL environment variable.
#url = "postgres://user:password@localhost/conduit"

[public]
listen = "127.0.0.1:8089"
workers = 12
backlog = 8192
services = [
  "User", "Profile", "Article",
  "Tag"
]

[public.cors]
origins = "*"
methods = [
  "GET", "HEAD", "POST", "OPTIONS", "PUT", "PATCH", "DELETE"
]
headers = [
  "Authorization", "Content-Type"
]
max-age = 3600

[User]

[Profile]
allow_update = true

[Article]
allow_update = true
allow_delete = true
